// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVbCMNieu_YM_B4EXi5fy1-9t_bfqN6-g',
    appId: '1:928550275862:web:fc7bfb191a83e5f9141e37',
    messagingSenderId: '928550275862',
    projectId: 'final-fbla',
    authDomain: 'final-fbla.firebaseapp.com',
    storageBucket: 'final-fbla.appspot.com',
    measurementId: 'G-C8WE45R067',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCERM-eVe7rvTZgoTvpa5JZumKej25_jac',
    appId: '1:928550275862:android:ac81440ff2d179c6141e37',
    messagingSenderId: '928550275862',
    projectId: 'final-fbla',
    storageBucket: 'final-fbla.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6M3Bk_SF6u_mn100v5irqSCb-GejqGs',
    appId: '1:928550275862:ios:6de6d6017bb86e71141e37',
    messagingSenderId: '928550275862',
    projectId: 'final-fbla',
    storageBucket: 'final-fbla.appspot.com',
    iosClientId: '928550275862-96vddbg6qmdh1h6d6lrg8iqefn6tkoc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalFbla',
  );
}
